[config]
default_to_workspace = false

[tasks.build-web]
command = "bash"
args = ["./build-web.sh"]

[tasks.build]
command = "cargo"
args = ["build", "--workspace", "--exclude", "menu"]
dependencies = ["build-web"]

[tasks.run]
command = "cargo"
args = ["run", "--bin", "barista-cli", "--", "serve", "-c", "example.yml"]
dependencies = ["build"]
env = { "MINED_LOG" = "info" }
